// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {services} from '../models';

export function AddWiki(arg1:models.Wiki):Promise<void>;

export function CheckPortsStatus():Promise<Array<services.PortInfo>>;

export function CreateNewWiki(arg1:string,arg2:string):Promise<string>;

export function DeleteWiki(arg1:string):Promise<void>;

export function ExportWikiToHTML(arg1:string):Promise<string>;

export function GetAllCategories():Promise<Array<string>>;

export function GetAllTags():Promise<Array<string>>;

export function GetAppVersion():Promise<string>;

export function GetPlatform():Promise<string>;

export function GetWikiStatus(arg1:string):Promise<string>;

export function GetWikis():Promise<Array<models.Wiki>>;

export function KillPortProcess(arg1:number):Promise<void>;

export function OpenFolder(arg1:string):Promise<void>;

export function OpenGitHubDesktop(arg1:string):Promise<void>;

export function OpenInfoFile(arg1:string):Promise<void>;

export function OpenVSCode(arg1:string):Promise<void>;

export function OpenWikiInNewWindow(arg1:string):Promise<void>;

export function OpenWikiWindow(arg1:string):Promise<void>;

export function RestartWiki(arg1:string):Promise<void>;

export function SelectFolder():Promise<string>;

export function StartWiki(arg1:string):Promise<void>;

export function StopWiki(arg1:string):Promise<void>;

export function UpdateWiki(arg1:models.Wiki):Promise<void>;

export function WindowClose():Promise<void>;

export function WindowMaximize():Promise<void>;

export function WindowMinimize():Promise<void>;

export function WindowToggleMaximize():Promise<void>;
