// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddWiki(arg1) {
  return window['go']['main']['App']['AddWiki'](arg1);
}

export function CheckPortsStatus() {
  return window['go']['main']['App']['CheckPortsStatus']();
}

export function CreateNewWiki(arg1, arg2) {
  return window['go']['main']['App']['CreateNewWiki'](arg1, arg2);
}

export function DeleteWiki(arg1) {
  return window['go']['main']['App']['DeleteWiki'](arg1);
}

export function ExportWikiToHTML(arg1) {
  return window['go']['main']['App']['ExportWikiToHTML'](arg1);
}

export function GetAllCategories() {
  return window['go']['main']['App']['GetAllCategories']();
}

export function GetAllTags() {
  return window['go']['main']['App']['GetAllTags']();
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetPlatform() {
  return window['go']['main']['App']['GetPlatform']();
}

export function GetWikiStatus(arg1) {
  return window['go']['main']['App']['GetWikiStatus'](arg1);
}

export function GetWikis() {
  return window['go']['main']['App']['GetWikis']();
}

export function KillPortProcess(arg1) {
  return window['go']['main']['App']['KillPortProcess'](arg1);
}

export function OpenFolder(arg1) {
  return window['go']['main']['App']['OpenFolder'](arg1);
}

export function OpenGitHubDesktop(arg1) {
  return window['go']['main']['App']['OpenGitHubDesktop'](arg1);
}

export function OpenInfoFile(arg1) {
  return window['go']['main']['App']['OpenInfoFile'](arg1);
}

export function OpenVSCode(arg1) {
  return window['go']['main']['App']['OpenVSCode'](arg1);
}

export function OpenWikiInNewWindow(arg1) {
  return window['go']['main']['App']['OpenWikiInNewWindow'](arg1);
}

export function OpenWikiWindow(arg1) {
  return window['go']['main']['App']['OpenWikiWindow'](arg1);
}

export function RestartWiki(arg1) {
  return window['go']['main']['App']['RestartWiki'](arg1);
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}

export function StartWiki(arg1) {
  return window['go']['main']['App']['StartWiki'](arg1);
}

export function StopWiki(arg1) {
  return window['go']['main']['App']['StopWiki'](arg1);
}

export function UpdateWiki(arg1) {
  return window['go']['main']['App']['UpdateWiki'](arg1);
}

export function WindowClose() {
  return window['go']['main']['App']['WindowClose']();
}

export function WindowMaximize() {
  return window['go']['main']['App']['WindowMaximize']();
}

export function WindowMinimize() {
  return window['go']['main']['App']['WindowMinimize']();
}

export function WindowToggleMaximize() {
  return window['go']['main']['App']['WindowToggleMaximize']();
}
